name = "birnam-twin"
version = "0.1.0"
main = "main.birnam"
source_roots = ["src"]
load = ["birnamTwin"]

[dependencies]
twin = { git = "https://github.com/chazu/birnam-alien-twin.git", rev = "0e93848210bbc6f88c0d72379fc047b39da23d65" }

[test]
sources = ["test/birnam-twin-test.birnam"]
